apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-init
data:
  init-master.sql: |
    CREATE USER 'repl'@'%' IDENTIFIED WITH mysql_native_password BY 'replpass';
    GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
    FLUSH PRIVILEGES;
