apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-init
data:
  init-slave.sql: |
    STOP SLAVE;

    CHANGE MASTER TO
      MASTER_HOST='mysql-master',
      MASTER_PORT=3306,
      MASTER_USER='repl',
      MASTER_PASSWORD='replpass',
      MASTER_LOG_FILE='binlog.000002',
      MASTER_LOG_POS=992;

    START SLAVE;
