apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      role: master
  template:
    metadata:
      labels:
        role: master
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          ports:
            - containerPort: 3306
          #volumeMounts:
          #  - name: data
          #    mountPath: /var/lib/mysql
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
            - name: config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: init-script
          configMap:
            name: mysql-master-init
        - name: config
          configMap:
            name: mysql-master-conf
