apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
  MYSQL_REPLICATION_USER: {{ .Values.mysql.replicationUser }}
  MYSQL_REPLICATION_PASSWORD: {{ .Values.mysql.replicationPassword }}
